name: Branch Tests

on:
  push:
    branches-ignore: [ main, master ]  # Don't run on main/master as ci.yml handles those
  pull_request:
    branches-ignore: [ main, master ]  # Don't run on PRs to main/master as ci.yml handles those

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      env:
        REDIS_URL: ${{ secrets.REDIS_URL || 'redis://localhost:6379' }} 