name: Branch Tests

on:
  # Only run on pull requests
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests  # Explicit name for the status check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      env:
        REDIS_URL: ${{ secrets.REDIS_URL || 'redis://localhost:6379' }} 